import Head from 'next/head'
import styles from '../styles/Home.module.css'
import * as React from 'react'
import Button from '@mui/material/Button'
import { CssBaseline, requirePropFactory } from '@mui/material'
import { ThemeProvider, createTheme } from "@mui/material/styles"
import Grid from '@mui/material/Grid'
import { Box } from '@mui/system'
import TextField from '@mui/material/TextField'
import MenuItem from '@mui/material/MenuItem'
import Image from 'next/image'

function a2tf(asciiInput) {
  return String.fromCharCode(asciiInput);
}

function t2af(textInput) {
  return textInput.charCodeAt();
}

function b2tf(binaryInput) {
  binaryInput = binaryInput.split(" ")
  var returnText = "";
  for (var i = 0; i < binaryInput.length; i++) {
    var deci = parseInt(binaryInput[i], 2)
    returnText = returnText + a2tf(deci)
  }
  return returnText
}

const translations = [
  {
    value: "B2T",
    label: "Binary to Text"
  },
  {
    value: "T2B",
    label: "Text to Binary"
  },
  {
    value: "H2T",
    label: "Hex to Text"
  },
  {
    value: "T2H",
    label: "Text to Hex"
  },
  {
    value: "A2T",
    label: "ASCII to Text"
  },
  {
    value: "T2A",
    label: "Text to ASCII"
  },
  {
    value: "M2T",
    label: "Morse to Text"
  },
  {
    value: "T2M",
    label: "Text to Morse"
  }
]

const frogBg = createTheme({
  palette: {
    background: {
      default: "#e4f0e2"
    }
  }
})

const duckBg = createTheme({
  palette: {
    background: {
      default: "#eef0e2"
    }
  }
})

const buttonTheme = createTheme({
  palette: {
    duck: {
      main: "#dec400",
      contrastText: '#000'
    },
    frog: {
      main: "#1e7022",
      contrastText: '#FFF'
    }
  }
})

export default function Home() {

  // States
  const [bgColor, setBgColor] = React.useState(frogBg);
  const [translation, setTranslation] = React.useState('B2T')
  var [value, setValue] = React.useState("")
  var [b2t, setb2t] = React.useState("")


  // inner functions
  const handleChange = e => {
    setTranslation(e.target.value)
  }

  const handleInput = e => {
    setValue(e.target.value)
  }

  const handleb2t = (value) => {
    setb2t(b2tf(value))
  }




  return (
    <ThemeProvider theme={bgColor}>
      <CssBaseline/>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Grid container>



          {/* SIDE BAR MENU */}
          <Grid item xs={3}>
            <div class="menu">
              <Box sx={{display: 'flex', flexDirection: "column" , alignContent: "space-between"}}>
                <Box sx={{display: 'flex', justifyContent: 'center'}}>
                  <Box component="form" 
                    sx={{'& .MuiTextField-root': {mt: 0, width: '23vw'}}}
                    noValidate
                    autoComplete='off'
                  >
                    <div>
                      <TextField
                        id="outlined-select-translations"
                        select
                        label="Translate"
                        value={translation}
                        onChange={handleChange}
                        // helperText="Please choose one of the methods"  
                      >
                        {translations.map((option) => (
                          <MenuItem key={option.value} value={option.value}>
                            {option.label}
                          </MenuItem>
                        ))}
                      </TextField>
                    </div>
                  </Box>
                </Box>
                <Box sx={{display: 'flex', justifyContent: 'center'}}>
                  <Image src="/dric.jpg" width="500px" height="500px"></Image>
                </Box>
                <Box sx={{display: 'flex', justifyContent: 'center'}}>
                  <Box sx={{'& .MuiButton-root': {mt: 0, width: '23vw'}}}>
                    <Button variant="contained" disableElevation>
                      Instructions
                    </Button>
                  </Box>
                </Box>
              </Box>
            </div>
          </Grid>

          {/* I/O STUFF */}
          <Grid item xs={9}>
            <Box sx={{display: 'flex', flexDirection: 'column', justifyContent: 'start'}}>
              <Box sx={{display: 'flex', justifyContent: 'center'}}>
                <Box component="form"
                  sx={{'& .MuiTextField-root': {mt: 3, width: '70vw'}}}
                  noValidate
                  autoComplete="off" 
                >
                  <div>
                    <TextField
                      id="outlined-multiline-input"
                      label="Input your Frog"
                      multiline
                      fullWidth
                      rows={8}
                      onChange={e => handleb2t(e.target.value)}  
                    >
                    </TextField>
                  </div>
                </Box>
              </Box>
              
              <Box sx={{display: 'flex', justifyContent: 'center'}}>
                <Box component="form"
                  sx={{'& .MuiTextField-root': {mt: 3, width: '70vw'}}} 
                  noValidate
                  autoComplete="off" 
                >
                  <div>
                    <TextField
                      id="outlined-multiline-output"
                      label="Out comes your Duck"
                      multiline
                      disabled
                      rows={8}
                      value={b2t}
                    >
                    </TextField>
                  </div>
                </Box>
              </Box>
            </Box>
          </Grid>
        </Grid>
      </main>
    </ThemeProvider>
    
  )
}
