import Head from 'next/head'
import styles from '../styles/Home.module.css'
// import globalcss from '../styles/globals.css'
import bootstrap from 'bootstrap/dist/css/bootstrap.css'
import script from 'next/script'
import React, { useState } from 'react';

export default function Home() {

    const [bgColor, setBgColor] = useState("green-bg")
    
    const changeToGreen = () => {
        setBgColor("green-bg")
    }

    const changeToYellow = () => {
        setBgColor("yellow-bg")
    }

  return (
    <div className={`${styles.container} ${bgColor}`}>
      <Head>
        <title>Frog To Duck</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="d-flex justify-content-between p-5">
        <div>
            <button type="button" class="p-4 my-2 me-4 btn btn-lg btn-outline-success" onClick={changeToGreen}>Frog 🐸</button>
            <button type="button" class="p-4 my-2 btn btn-lg btn-outline-warning" onClick={changeToYellow}>Duck 🦆</button>
        </div>
        <div className="bg-primary text-light">
            ---------------- Navbar stuff --------------------
        </div>
      </main>

      <footer>
        
      </footer>

    </div>
  )
}
